# Generated by Django 2.2 on 2019-11-25 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Datos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='clave',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='persona',
            name='usuario',
            field=models.CharField(default='', max_length=50),
        ),
    ]
